sudo: false
dist: xenial

language: node_js
node_js:
  - lts/*

addons:
  chrome: stable
  firefox: latest

install:
  - npm install opencollective-postinstall
  - npm prune
  - npm install

script:
  - npm run lint || travis_terminate 1
  - npm run build || travis_terminate 1
  - npm run test || travis_terminate 1
  - npm run docs || travis_terminate 1

cache:
  directories:
    - node_modules
